CACHE_PREFIX_JOB = "job:"
CACHE_PREFIX_CANDIDATE = "candidate:"
IDEMPOTENT_KEY_PREFIX = "idem:"
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
DEFAULT_RAG_TOP_K = 30
DEFAULT_RERANK_TOP_N = 10
DEFAULT_RERANK_THRESHOLD = 0.4
DEBATE_STD_THRESHOLD = 15.0
LOCK_TIMEOUT_SECONDS = 10
SESSION_TTL = 24 * 3600
WEIGHTS_TECH = {"skill": 0.35, "experience": 0.35, "culture_fit": 0.15, "stability": 0.15}
WEIGHTS_BY_CATEGORY = {
    "tech": WEIGHTS_TECH,
    "management": WEIGHTS_TECH,  # 可调整
    "design": WEIGHTS_TECH,
    "general": WEIGHTS_TECH
}
DEBATE_MAX_ROUNDS = 2